### PR TITLE
Add --filter-patthern option

### PR DESCRIPTION
**Pull request by jorgebastida**
Make is possible to filter events using a CloudWatch Logs filter pattern. As requested on #25

### CODE REVIEW

**Comment by jorgebastida** [comment]
I've play with this a bit and it looks like it is working... for example to only get the "report" lines from a lambda log...

``$ awslogs get XXX --filter-pattern="[r=REPORT,...]"``

Could you please give it a try before merging this on master?

**Comment by johnhamelink** [comment]
Do you have any instructions on how to run this from source? I'll give it a try for my use-case if so.

**Comment by jorgebastida** [comment]
Sure, you only need to clone this repo, move to this branch and install the development version.
```bash
git clone git@github.com:jorgebastida/awslogs.git
git co -t origin feature/filter-pattern
cd awslogs
python setup.py develop
```
This should do the trick. Once you are done, you can install the pypi version using ``pip install awslogs``

**Comment by johnhamelink** [comment]
@jorgebastida I tried `awslogs get production_api_web --filter-pattern="groups"` and it seems to work :smile:

**Comment by adamchainz** [comment]
Works for me too! Looking forward to PyPI deploy so I can push this to developers in my team.

**Comment by jorgebastida** [comment]
I did publish ``0.2`` yesterday! Let me know if everything goes ok :)

**Pull request merged**
